[2024-02-29T07:04:42.343+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.remove_airlines_file manual__2024-02-29T06:56:48.415625+00:00 [queued]>
[2024-02-29T07:04:42.359+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.remove_airlines_file manual__2024-02-29T06:56:48.415625+00:00 [queued]>
[2024-02-29T07:04:42.360+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-02-29T07:04:42.421+0000] {taskinstance.py:2214} INFO - Executing <Task(WasbDeleteBlobOperator): remove_airlines_file> on 2024-02-29 06:56:48.415625+00:00
[2024-02-29T07:04:42.427+0000] {standard_task_runner.py:60} INFO - Started process 276 to run task
[2024-02-29T07:04:42.431+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'AIRLINES_ETL_PIPELINE', 'remove_airlines_file', 'manual__2024-02-29T06:56:48.415625+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/AIRLINES_DATA_ETL_DAG.py', '--cfg-path', '/tmp/tmpx45vy7bz']
[2024-02-29T07:04:42.433+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask remove_airlines_file
[2024-02-29T07:04:42.548+0000] {task_command.py:423} INFO - Running <TaskInstance: AIRLINES_ETL_PIPELINE.remove_airlines_file manual__2024-02-29T06:56:48.415625+00:00 [running]> on host 586f09520b0e
[2024-02-29T07:04:43.457+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='AIRLINES_ETL_PIPELINE' AIRFLOW_CTX_TASK_ID='remove_airlines_file' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T06:56:48.415625+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T06:56:48.415625+00:00'
[2024-02-29T07:04:43.458+0000] {wasb_delete_blob.py:67} INFO - Deleting blob: Airlines_Data.csv.gz
 in wasb://raw
[2024-02-29T07:04:43.479+0000] {base.py:83} INFO - Using connection ID 'azure_blob_storage' for task execution.
[2024-02-29T07:04:43.703+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/operators/wasb_delete_blob.py", line 70, in execute
    hook.delete_file(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 534, in delete_file
    raise AirflowException(f"Blob(s) not found: {blob_name}")
airflow.exceptions.AirflowException: Blob(s) not found: Airlines_Data.csv.gz
[2024-02-29T07:04:43.710+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AIRLINES_ETL_PIPELINE, task_id=remove_airlines_file, execution_date=20240229T065648, start_date=20240229T070442, end_date=20240229T070443
[2024-02-29T07:04:43.778+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task remove_airlines_file (Blob(s) not found: Airlines_Data.csv.gz; 276)
[2024-02-29T07:04:43.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-29T07:04:43.846+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
