[2024-02-28T07:39:30.254+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-28T07:39:24.252024+00:00 [queued]>
[2024-02-28T07:39:30.269+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-28T07:39:24.252024+00:00 [queued]>
[2024-02-28T07:39:30.270+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-28T07:39:30.364+0000] {taskinstance.py:2214} INFO - Executing <Task(SnowflakeOperator): blob_to_snowflake_stg> on 2024-02-28 07:39:24.252024+00:00
[2024-02-28T07:39:30.372+0000] {standard_task_runner.py:60} INFO - Started process 171 to run task
[2024-02-28T07:39:30.377+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'AIRLINES_ETL_PIPELINE', 'blob_to_snowflake_stg', 'manual__2024-02-28T07:39:24.252024+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/AIRLINES_DATA_ETL_DAG.py', '--cfg-path', '/tmp/tmpzupattah']
[2024-02-28T07:39:30.382+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask blob_to_snowflake_stg
[2024-02-28T07:39:30.502+0000] {task_command.py:423} INFO - Running <TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-28T07:39:24.252024+00:00 [running]> on host c262eab4accf
[2024-02-28T07:39:30.632+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'blob_to_snowflake_stg', field 'sql'. Template: 'airflow/dags/sql/Airlines_ingest_query.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: airflow/dags/sql/Airlines_ingest_query.sql
[2024-02-28T07:39:30.666+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2357, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2907, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: airflow/dags/sql/Airlines_ingest_query.sql
[2024-02-28T07:39:30.686+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AIRLINES_ETL_PIPELINE, task_id=blob_to_snowflake_stg, execution_date=20240228T073924, start_date=20240228T073930, end_date=20240228T073930
[2024-02-28T07:39:30.779+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task blob_to_snowflake_stg (airflow/dags/sql/Airlines_ingest_query.sql; 171)
[2024-02-28T07:39:30.792+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-28T07:39:30.818+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
