[2024-02-28T07:13:55.603+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-28T07:13:44.311501+00:00 [queued]>
[2024-02-28T07:13:55.619+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-28T07:13:44.311501+00:00 [queued]>
[2024-02-28T07:13:55.620+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-28T07:13:56.072+0000] {taskinstance.py:2214} INFO - Executing <Task(SnowflakeOperator): blob_to_snowflake_stg> on 2024-02-28 07:13:44.311501+00:00
[2024-02-28T07:13:56.093+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-02-28T07:13:56.178+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'AIRLINES_ETL_PIPELINE', 'blob_to_snowflake_stg', 'manual__2024-02-28T07:13:44.311501+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/AIRLINES_DATA_ETL_DAG.py', '--cfg-path', '/tmp/tmp17acgc24']
[2024-02-28T07:13:56.198+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask blob_to_snowflake_stg
[2024-02-28T07:13:56.761+0000] {task_command.py:423} INFO - Running <TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-28T07:13:44.311501+00:00 [running]> on host ad8d771dc65a
[2024-02-28T07:13:57.274+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='AIRLINES_ETL_PIPELINE' AIRFLOW_CTX_TASK_ID='blob_to_snowflake_stg' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T07:13:44.311501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T07:13:44.311501+00:00'
[2024-02-28T07:13:57.279+0000] {sql.py:276} INFO - Executing: Airlines_data_ingest_query.txt
[2024-02-28T07:13:57.314+0000] {base.py:83} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-02-28T07:13:57.643+0000] {base.py:83} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-02-28T07:13:57.644+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.11.8, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-02-28T07:13:57.646+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-28T07:13:58.924+0000] {cursor.py:1032} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-28T07:13:59.053+0000] {cursor.py:1045} INFO - query execution done
[2024-02-28T07:13:59.056+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-28T07:13:59.057+0000] {sql.py:457} INFO - Running statement: Airlines_data_ingest_query.txt, parameters: None
[2024-02-28T07:13:59.057+0000] {cursor.py:1032} INFO - query: [Airlines_data_ingest_query.txt]
[2024-02-28T07:13:59.150+0000] {cursor.py:1045} INFO - query execution done
[2024-02-28T07:13:59.154+0000] {connection.py:734} INFO - closed
[2024-02-28T07:13:59.196+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-02-28T07:13:59.247+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 390, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01b2a5d1-0001-18d1-0000-000393fa7061: SQL compilation error:
syntax error line 1 at position 0 unexpected 'Airlines_data_ingest_query'.
[2024-02-28T07:13:59.266+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AIRLINES_ETL_PIPELINE, task_id=blob_to_snowflake_stg, execution_date=20240228T071344, start_date=20240228T071355, end_date=20240228T071359
[2024-02-28T07:13:59.353+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task blob_to_snowflake_stg (001003 (42000): 01b2a5d1-0001-18d1-0000-000393fa7061: SQL compilation error:
syntax error line 1 at position 0 unexpected 'Airlines_data_ingest_query'.; 96)
[2024-02-28T07:13:59.401+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-28T07:13:59.440+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
